### ISSUE TITLE
project.godot, icon.svg (and its import file), and the demo file are all part of the release on the asset store

### ISSUE THREAD

**Issue by ruguysgoingtrickortreating** [dominiks/rpc-await#1]
![image](https://github.com/dominiks/rpc-await/assets/71863699/5ede7b98-aace-4657-a071-8f93e6554b34)
obviously this is undesired if you're trying to install into an existing project

**Comment by dominiks** [comment]
Thanks for reporting! I updated the `.gitattributes` file with the (new?) recommendation for addons. The change is now live in the asset library and it only includes the `addon` directory when installing.
